apiVersion: apps/v1
kind: Deployment
metadata:
  name: intapi-deployment
spec:
  selector:
    matchLabels:
      app: intapi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: intapi-app
    spec:
      containers:
      - name: intapi
        image: lidorabo/docker_repo:intapi_{{version}}
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000

