apiVersion: apps/v1
kind: Deployment
metadata:
  name: intapi-deployment
spec:
  selector:
    matchLabels:
      app: intapi-app
  replicas: 1
  template:
    metadata:
      labels:
        app: intapi-app
    spec:
      containers:
      - name: intapi
        image: lidorabo/docker_repo:intapi_1.0.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: intapi-app
  name: intapi-svc
  namespace: default
spec:
  type: NodePort    # use LoadBalancer as type here
  externalIPs:
     - 10.0.2.141
  ports:
    - port: 3000
      nodePort: 30002
  selector:
    app: intapi-app
